# Generated by Django 4.2.28 on 2026-02-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
